// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bdm_stat_cpp
double bdm_stat_cpp(NumericVector Y, IntegerVector A, IntegerVector batch_id);
RcppExport SEXP _AdaReg_bdm_stat_cpp(SEXP YSEXP, SEXP ASEXP, SEXP batch_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batch_id(batch_idSEXP);
    rcpp_result_gen = Rcpp::wrap(bdm_stat_cpp(Y, A, batch_id));
    return rcpp_result_gen;
END_RCPP
}
// ipw_cpp
List ipw_cpp(NumericVector Y, IntegerVector A, NumericVector sampling_prob, IntegerVector batch_id, bool one_batch, int batch_output);
RcppExport SEXP _AdaReg_ipw_cpp(SEXP YSEXP, SEXP ASEXP, SEXP sampling_probSEXP, SEXP batch_idSEXP, SEXP one_batchSEXP, SEXP batch_outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampling_prob(sampling_probSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batch_id(batch_idSEXP);
    Rcpp::traits::input_parameter< bool >::type one_batch(one_batchSEXP);
    Rcpp::traits::input_parameter< int >::type batch_output(batch_outputSEXP);
    rcpp_result_gen = Rcpp::wrap(ipw_cpp(Y, A, sampling_prob, batch_id, one_batch, batch_output));
    return rcpp_result_gen;
END_RCPP
}
// weighted_ipw_cpp
NumericMatrix weighted_ipw_cpp(NumericVector Y, IntegerVector A, NumericVector sampling_prob, IntegerVector batch_id, String weighting);
RcppExport SEXP _AdaReg_weighted_ipw_cpp(SEXP YSEXP, SEXP ASEXP, SEXP sampling_probSEXP, SEXP batch_idSEXP, SEXP weightingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampling_prob(sampling_probSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batch_id(batch_idSEXP);
    Rcpp::traits::input_parameter< String >::type weighting(weightingSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_ipw_cpp(Y, A, sampling_prob, batch_id, weighting));
    return rcpp_result_gen;
END_RCPP
}
// plugin_bootstrap_cpp
NumericVector plugin_bootstrap_cpp(NumericVector mean_estimate, NumericVector variance_estimate, double eps, double fs_p, int B, String normalization, double h, String weighting, String type);
RcppExport SEXP _AdaReg_plugin_bootstrap_cpp(SEXP mean_estimateSEXP, SEXP variance_estimateSEXP, SEXP epsSEXP, SEXP fs_pSEXP, SEXP BSEXP, SEXP normalizationSEXP, SEXP hSEXP, SEXP weightingSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mean_estimate(mean_estimateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type variance_estimate(variance_estimateSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type fs_p(fs_pSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< String >::type normalization(normalizationSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< String >::type weighting(weightingSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(plugin_bootstrap_cpp(mean_estimate, variance_estimate, eps, fs_p, B, normalization, h, weighting, type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AdaReg_bdm_stat_cpp", (DL_FUNC) &_AdaReg_bdm_stat_cpp, 3},
    {"_AdaReg_ipw_cpp", (DL_FUNC) &_AdaReg_ipw_cpp, 6},
    {"_AdaReg_weighted_ipw_cpp", (DL_FUNC) &_AdaReg_weighted_ipw_cpp, 5},
    {"_AdaReg_plugin_bootstrap_cpp", (DL_FUNC) &_AdaReg_plugin_bootstrap_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_AdaReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
