# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib AdaReg, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

bdm_stat_cpp <- function(Y, A, batch_id) {
    .Call(`_AdaReg_bdm_stat_cpp`, Y, A, batch_id)
}

ipw_cpp <- function(Y, A, sampling_prob, batch_id, one_batch = FALSE, batch_output = 1L) {
    .Call(`_AdaReg_ipw_cpp`, Y, A, sampling_prob, batch_id, one_batch, batch_output)
}

weighted_ipw_cpp <- function(Y, A, sampling_prob, batch_id, weighting = "aw") {
    .Call(`_AdaReg_weighted_ipw_cpp`, Y, A, sampling_prob, batch_id, weighting)
}

plugin_bootstrap_cpp <- function(mean_estimate, variance_estimate, eps, fs_p, B = 2000L, normalization = "normalized", h = 0.0, weighting = "aw", type = "eps_greedy") {
    .Call(`_AdaReg_plugin_bootstrap_cpp`, mean_estimate, variance_estimate, eps, fs_p, B, normalization, h, weighting, type)
}

